### ISSUE TITLE
Invitation for joining CODE++

### ISSUE THREAD

**Issue by cixtor** [The-CODE-Plus-Plus-Community/Support#25]
### First Name : 

cixtor

### Last Name :

_

### Let us understand your motive :

I have been an active member of the open-source community on GitHub and other platforms, and it is always a joy to find like-minded people willing to share knowledge and experiences. I would love to join thir GitHub organization to help many more developers become excellent open-source maintainers.

### Tech Stack you prefer :

C++

**Comment by Subhampreet** [comment]
Hey 🦊,

Welcome to CODE++ Community 🎉🎉🎉!!!

Check your mail and Accept the invitation to the community, Hope you contribute to the projects in the community and make this community big 🍀.

Regards,
CODE++
