### ISSUE TITLE
Invitation for joining CODE++

### ISSUE THREAD

**Issue by Sugamgoel28** [The-CODE-Plus-Plus-Community/Support#43]
Sugam Goel

Being part of a GitHub organization like Code++ will allow me to connect with other developers who share my interest in programming. I'd like to engage in discussions, participate in events or workshops, and build relationships with professionals in the field.

C++, Html, CSS, Javascript.

**Comment by JAYKALIA007** [comment]
I've sent an invite. Kindly check.
