### ISSUE TITLE
Invitation for joining CODE++

### ISSUE THREAD

**Issue by Mubshr07** [The-CODE-Plus-Plus-Community/Support#55]
### Let us understand your motive :
Hello, I want to contribute to open-source projects. I want to build a good portfolio on Git Hub, I need PR, issues, contributions, and all other stuff. Please consider my request and send me the invitation.

### Tech Stack you prefer :
C++, Python, PHP, Front-end Technologies

**Comment by Subhampreet** [comment]
Invitation sent via mail 🦊

**Comment by Mubshr07** [comment]
Thank you. hope i see an interesting project and send you email about my contribution in it.
